name="aiwpa-analyzer"
main="src/index.ts"

compatibility_date = "2022-11-22"
compatibility_flags = [ "streams_enable_constructors" ]

[[d1_databases]]
binding = "DB"
database_name = "emailsv2"
database_id = "6193778c-f94d-46c2-a4e0-81dc2c1d6c47"
